#!/bin/bash
# setup.sh — Bootstrap the Hermes Agent Development Workflow for a project.
#
# Usage:
#   ./setup.sh --repo "owner/project" --dir "/path/to/project"
#
# This copies portable profiles, skills, and scripts into ~/.hermes,
# templating cron jobs with the project's values. Secrets must be
# configured manually in ~/.hermes/profiles/*/.env afterward.

set -euo pipefail

REPO=""
PROJECT_DIR=""
BOARD_SLUG=""
STAGING_URL=""
DRY_RUN=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --repo) REPO="$2"; shift 2 ;;
        --dir) PROJECT_DIR="$2"; shift 2 ;;
        --board) BOARD_SLUG="$2"; shift 2 ;;
        --staging-url) STAGING_URL="$2"; shift 2 ;;
        --dry-run) DRY_RUN=true; shift ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

if [ -z "$REPO" ] || [ -z "$PROJECT_DIR" ]; then
    echo "Usage: $0 --repo owner/project --dir /path/to/project [--board slug] [--staging-url url]"
    exit 1
fi

BOARD_SLUG="${BOARD_SLUG:-$(basename "$PROJECT_DIR")-dev}"
STAGING_URL="${STAGING_URL:-}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HERMES="$HOME/.hermes"

echo "============================================"
echo " Hermes Agent Development Workflow Setup"
echo "============================================"
echo ""
echo "  Project:     $REPO"
echo "  Directory:   $PROJECT_DIR"
echo "  Board:       $BOARD_SLUG"
echo "  Staging URL: ${STAGING_URL:-<not configured>}"
echo ""

# ---- Prerequisites ----
check_cmd() {
    if ! command -v "$1" &>/dev/null; then
        echo "❌ Missing prerequisite: $1"
        exit 1
    fi
}
check_cmd git
check_cmd gh
check_cmd hermes
check_cmd sqlite3
check_cmd python3
check_cmd jq
echo "✓ Prerequisites met"
echo ""

# ---- Copy profiles ----
copy_profile() {
    local name="$1"
    local src="$SCRIPT_DIR/profiles/$name"
    local dst="$HERMES/profiles/$name"

    if [ ! -d "$src" ]; then
        echo "  ⚠ $name: not found, skipping"
        return
    fi

    mkdir -p "$dst"

    # SOUL.md
    if [ -f "$src/SOUL.md" ]; then
        cp "$src/SOUL.md" "$dst/SOUL.md"
    fi

    # Scripts
    if [ -d "$src/scripts" ]; then
        mkdir -p "$dst/scripts"
        cp -r "$src/scripts/"* "$dst/scripts/" 2>/dev/null || true
        find "$dst/scripts" -name "*.py" -o -name "*.sh" | xargs chmod +x 2>/dev/null || true
    fi

    # Cron (template → real)
    if [ -f "$src/cron/jobs.json.template" ]; then
        mkdir -p "$dst/cron"
        sed -e "s|\${HERMES_PROJECT_REPO:-$HERMES_PROJECT_REPO}|$REPO|g" \
            -e "s|\${HERMES_PROJECT_DIR:-$HERMES_PROJECT_DIR}|$PROJECT_DIR|g" \
            -e "s|\${HERMES_KANBAN_BOARD:-$HERMES_KANBAN_BOARD}|$BOARD_SLUG|g" \
            -e "s|\${HERMES_STAGING_URL:-staging.my-project.com}|${STAGING_URL:-staging.example.com}|g" \
            "$src/cron/jobs.json.template" > "$dst/cron/jobs.json"
    fi

    echo "  ✓ $name"
}

echo "Installing profiles..."
copy_profile "orchestrator"
copy_profile "qa"
copy_profile "coder"
copy_profile "code-reviewer"
echo ""

# ---- Copy skills ----
echo "Installing skills..."
if [ -d "$SCRIPT_DIR/skills" ]; then
    mkdir -p "$HERMES/profiles/orchestrator/skills"
    for skill_dir in "$SCRIPT_DIR/skills/"*/*; do
        [ -d "$skill_dir" ] || continue
        skill_name="$(basename "$(dirname "$skill_dir")")/$(basename "$skill_dir")"
        dst="$HERMES/profiles/orchestrator/skills/$skill_name"
        rm -rf "$dst" 2>/dev/null || true
        cp -r "$skill_dir" "$dst"
        echo "  ✓ $skill_name"
    done
fi
echo ""

# ---- Create .env template ----
ENV_FILE="$HERMES/profiles/orchestrator/.env"
if [ ! -f "$ENV_FILE" ]; then
    cat > "$ENV_FILE" << EOF
# Hermes Agent Workflow — Project Secrets
# Generated by hermes-dev-workflow setup.sh

# GitHub token for API access (gh CLI)
GITHUB_TOKEN=

# OpenRouter API key (for LLM access)
OPENROUTER_API_KEY=

# Telegram bot token (for cron notifications)
TELEGRAM_BOT_TOKEN=

# Staging database URL (for QA DB-layer verification)
NEON_DATABASE_URL=
EOF
    echo "✓ Created .env template at $ENV_FILE"
    echo "  ⚠  Edit this file with your actual secrets before enabling cron jobs."
else
    echo "⚠ $ENV_FILE already exists — not overwriting."
fi
echo ""

# ---- Initialize kanban board ----
if ! hermes kanban boards list 2>/dev/null | grep -q "$BOARD_SLUG"; then
    hermes kanban boards create "$BOARD_SLUG" 2>/dev/null || true
    echo "✓ Kanban board '$BOARD_SLUG' created"
else
    echo "✓ Kanban board '$BOARD_SLUG' already exists"
fi
echo ""

# ---- Done ----
echo "============================================"
echo " Setup Complete!"
echo "============================================"
echo ""
echo "Next steps:"
echo "  1. Edit secrets:     vim ~/.hermes/profiles/orchestrator/.env"
echo "  2. Verify config:    hermes config get openrouter.api_key"
echo "  3. Start gateway:    hermes gateway start"
echo "  4. Test ingestion:   gh issue create --repo $REPO --title 'Test' --label ready-for-agent"
echo ""
echo "Cron jobs will start on next gateway restart. Monitor with:"
echo "  hermes cron list"
echo ""
